config/routes.rb
Rails.application.routes.draw do
  resources :feedbacks
  resources :bookings
  resources :routes
  get "home/index"
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  root to: "home#index"


  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :route

  # Ensure that booked_at is present
  validates :booked_at, presence: true
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_booking, only: %i[show edit update destroy]

  # GET /bookings
  def index
    # Show only current user's reservation
    @bookings = current_user.bookings
  end

  # GET /bookings/1
  def show
  end

  # GET /bookings/new
  def new
    @booking = current_user.bookings.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  def create
    # Create reservation
    @booking = current_user.bookings.new(booking_params)

    respond_to do |format|
      if @booking.save
        format.html { redirect_to @booking, notice: "Booking was successfully created." }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: "Booking was successfully updated." }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  def destroy
    @booking.destroy

    respond_to do |format|
      format.html { redirect_to bookings_path, notice: "Booking was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    # Set the booking using the current user's bookings
    def set_booking
      @booking = current_user.bookings.find(params[:id])
    end

    # Permit only trusted parameters. Note: :user_id is omitted because it is set automatically
    def booking_params
      params.require(:booking).permit(:route_id, :status, :booked_at)
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_booking.html.erb
<div id="<%= dom_id booking %>">
  <p>
    <strong>Route:</strong>
    <%= booking.route_id %>
  </p>

  <p>
    <strong>User:</strong>
    <%= booking.user_id %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= booking.status %>
  </p>

  <p>
    <strong>Booked at:</strong>
    <%= booking.booked_at %>
  </p>

</div>

app/views/bookings/_form.html.erb
<%= form_with(model: booking) do |form| %>
  <% if booking.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
        <% booking.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :route_id, style: "display: block" %>
    <%= form.text_field :route_id %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status %>
  </div>

  <div>
    <%= form.label :booked_at, style: "display: block" %>
    <%= form.datetime_field :booked_at %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<% content_for :title, "Editing booking" %>

<h1>Editing booking</h1>

<%= render "form", booking: @booking %>

<br>

<div>
  <%= link_to "Show this booking", @booking %> |
  <%= link_to "Back to bookings", bookings_path %>
</div>

app/views/bookings/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Bookings" %>

<h1>Bookings</h1>

<div id="bookings">
  <% @bookings.each do |booking| %>
    <%= render booking %>
    <p>
      <%= link_to "Show this booking", booking %>
    </p>
  <% end %>
</div>

<%= link_to "New booking", new_booking_path %>

app/views/bookings/new.html.erb
<% content_for :title, "New booking" %>

<h1>New booking</h1>

<%= render "form", booking: @booking %>

<br>

<div>
  <%= link_to "Back to bookings", bookings_path %>
</div>

app/views/bookings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @booking %>

<div>
  <%= link_to "Edit this booking", edit_booking_path(@booking) %> |
  <%= link_to "Back to bookings", bookings_path %>

  <%= button_to "Destroy this booking", @booking, method: :delete %>
</div>